server:
  port: 8002

spring:
  application:
    name: service-oss

  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.103:8848

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI4GCPPc9HFVmbHRxbyvUu
      keysecret: cd6NZngZZfolPEuH7lOVA2ZK6IFO2R
      bucketname: mymooc