# 服务器端口
server:
  port: 8007

wx:
  pay:
    appid: wx74862e0dfcf69954
    partner: 1558950191
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    notifyurl: http://guli.shop/api/order/weixinPay/weixinNotify
# 服务名
spring:
  application:
    name: service-order
  # nacos服务地址
  #spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.103:8848


  # 环境设置 : dev、test、prod
  profiles:
    active: dev

  # 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.103:12345/mymooc?serverTimezone=GMT%2B8
    username: root
    password: sfy1314
  redis:
    host: 192.168.10.103
    port: 6379

    timeout: 1800000


  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:com/xmchx/order/mapper/xml/*.xml

#开启熔断机制
feign:
  hystrix:
    enabled: true